"""initial epicimage table

Revision ID: 1aaec4db9f2c
Revises: 
Create Date: 2022-10-08 22:29:20.855963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaec4db9f2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epic_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.BigInteger(), nullable=True),
    sa.Column('taken_datetime', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=6), nullable=True),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epic_metadata')
    # ### end Alembic commands ###
